FriskByBergen/friskby

friskby/urls.py, sensor/templates/sensor/keys/overview.html, sensor/tests/context.py, sensor/tests/test_key_view.py, sensor/view/keys.py, sensor/view/urls.py
Very basic HTML view of the currently active keys. Requires login. Will extend with reset() functionality. Should probably also add created_data and modified_date to the keys.
=> Api key view

friskby/templates/friskby/main.html, sensor/api/api_views.py, sensor/api/info_serializers.py, sensor/migrations/0020_sensor_on_line.py, sensor/models.py, sensor/tests/test_api_data.py, sensor/tests/test_api_info.py
Added bool flag `on_line` to the Sensor model.
=> Sensor online

sensor/admin.py
This required initializing a select box with O(many) elements - which essentially led the whole thing to timeout.
=> Removed data_info field from DataValue admin model

friskby/templates/friskby/main.html, sensor/api/api_views.py, sensor/models.py, sensor/tests/test_api_data.py
With this the /api/reading/$sensor/ endpoint accepts a num=??? url parameter to get the last num values.
=> Reading limit

README.md, init_env.sh.template
Added README document - with basic 'getting started' information.
=> Updated README

README.md, init_env.sh.template
* Added `pip install -r req` to readme
* added example-url to `init_env_sh_template`
=> Added pip and example to readme and template

git_version/tests/test_git_version.py, plot/lib.py, plot/tests/context.py, plot/tests/test_device_plot.py, sensor/tests/context.py
Have added some `@skip()` decorators to enable offline testing + fixed(???) plotly plots.
=> Offline testing + plotly testing

friskby/friskby_urls.py, friskby/tests/context.py, friskby/tests/test_quick_view.py, friskby/views/quick.py
Some changes to the `quick`view:
1. Added simple get test.
2. Named url.
3. Removed raw sql - use Django orm.
Did not really understand the quick method, in particular it seems to fetch data for two weeks from the DB, but only one value is actually returned?
=> Removed raw sql

friskby/templates/friskby/quick.html, friskby/views/quick.py
Use query parameters to navigate in time and sensors through links in page.
=> Only fetch one sensortype at a time.

sensor/models.py, sensor/tests/test_rawdata.py
One more PR in the long series of making the RawData table slimmer and (hopefully ...) faster.
=> Will not store data with invalid format.

friskby/templates/friskby/quick.html, friskby/views/quick.py
and print correct name in the one remaining. micro meter is correct I hope.
=> Remove double value column

friskby/views/quick.py, sensor/models.py
Added timezone implementation to use the timezone of settings.TIME_ZONE
=> WIP: Changed the timestamp in Quick to use the timezone.

friskby/static/css/friskby.css, friskby/templates/friskby/quick.html
A few fixes and some minor cosmetic changes.
=> Minor fixes and cosmetics.

friskby/views/quick.py
Fixing (hopefully) https://github.com/FriskByBergen/friskby/issues/161
=> Updated quick view to show last measurement in table (not first)

friskby/static/js/quick/map.js
I fixed the function according to what I think is the purpose of it. @mortalisk can you have a look? I may have misunderstood.. If so we can delete this PR.
=> Changed the function normalize of map.js

friskby/GW/air_in_bergen.py
I have no idea where this is run, but if it's not crucial that we have the `00:00` timestamp, then it's simpler to replace it with `23:59` than it is to take `current_date - 1 day`
=> replace 00:00 with 23:59 because

friskby/GW/air_in_bergen.py
=> revert fix, add tz aware today for air bergen

friskby/friskby_urls.py, friskby/static/js/median/chart.js, friskby/templates/friskby/median.html, friskby/views/__init__.py, friskby/views/median.py
This is proof-of-concept trend.  Will take median, will add prediction later.
=> Median summary page

friskby/static/js/median/chart.js, friskby/views/median.py
plot areasplinerange for error
delta = every 60 min
now, period and delta are ready to be taken out as parameter for the api
=> Plot area instead of errorbar

friskby/static/js/quick/chart.js, friskby/views/median.py
This is NJs device, goes into the default list
=> Added FriskPI05 as default

friskby/templates/friskby/median.html, friskby/templates/friskby/quick.html, friskby/views/median.py
Exposed `delta` into `GET`.  Added link from quick to median.
=> Expose median delta

friskby/static/js/quick/chart.js, friskby/static/js/quick/map.js, friskby/templates/friskby/median.html, friskby/views/median.py
Also removed the numbers from the map.  They're not readable, and you can find them in the table.
We need to do improve the map, perhaps with the use of Voronoi?
=> Sasak default and pm25 trend

friskby/static/js/quick/map.js
Small change to better the symbol colors in the map.
=> Made the value coloring in the map fresher.

friskby/static/js/quick/map.js
Changed the map tiles so that the value symbols are more visible.
=> Changed the map tiles to Stamens toner-lite.

friskby/static/js/quick/map.js
@pgdr this works fine for me and it should work. Does it work for you?
=> Fixed the stamen layer config for OpenLayers.

friskby/views/median.py
trivial and minor; will self merge immediately
=> fix s_id to sensor in median/trend view

friskby/templates/friskby/quick.html, sensor/api/api_views.py, sensor/api/urls.py, sensor/models.py, sensor/templates/sensor/device.html, sensor/tests/context.py, sensor/tests/test_api_endpoint.py, sensor/tests/test_device.py, sensor/tests/test_device_info.py, sensor/view/urls.py, sensor/view/views.py
Small start of API for device information.
OK: Very basic api usage/example added for devices. You can click on a device on the front page, and come to an information page. Looks like .... - but illustrates the point.
When goint further with API I think we should be strict about using the django url / reverse machinery.
=> Device api

friskby/templates/friskby/quick.html, sensor/view/views.py
The link to device info at the front page failed - for some reason, temporarily disabling it.
=> Revert device api

sensor/api/api_views.py, sensor/templates/sensor/device.html, sensor/tests/test_device.py, sensor/tests/test_device_info.py
API - work; freaking freaking difficult.
=> Fixed the micro Device API

friskby/static/js/device/chart.js, friskby/tests/test_quick_view.py, friskby/views/quick.py, sensor/api/serializers.py, sensor/sample.py, sensor/templates/sensor/device.html, sensor/tests/test_device_info.py, sensor/view/views.py
Started on plotting for one single device.
=> Device plot
